#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && cd ../ > /dev/null && pwd )"

pushd $DIR

sudo nginx -c ./nginx.conf -p `pwd` -s stop
sudo nginx -c ~/etheruemcrowd/nginx.conf -p `pwd`

popd
